{% set name = "vulp" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vulp-{{ version }}.tar.gz
  sha256: 856261a54a51d19bad9c5c09f2c6d5a51f04834b6d15a4fb974b39953e2b3679

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.7
    - msgpack-python >=1.0.2

test:
  imports:
    - vulp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/vulp
  summary: Real-time motion control for Python.
  dev_url: https://github.com/upkie/vulp
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
