{% set name = "vulp" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vulp-{{ version }}.tar.gz
  sha256: 7a2b3695ffbe80927ca572410ec6c4ce2a0110c62bad76ded92314d5ce78f599

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.7
    - msgpack-python >=1.0.2

test:
  imports:
    - vulp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/vulp
  summary: Real-time motion control for Python.
  dev_url: https://github.com/upkie/vulp
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
